# 1. Data Exploration and Preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df= pd.read_csv("Alphabets_data.csv")
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [3]:
df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [4]:
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [5]:
df.dtypes

letter    object
xbox       int64
ybox       int64
width      int64
height     int64
onpix      int64
xbar       int64
ybar       int64
x2bar      int64
y2bar      int64
xybar      int64
x2ybar     int64
xy2bar     int64
xedge      int64
xedgey     int64
yedge      int64
yedgex     int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [7]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998     True
19999    False
Length: 20000, dtype: bool

In [8]:
df.duplicated().sum()

1332

In [9]:
df=df.drop_duplicates()

In [10]:
df.duplicated().sum()

0

In [11]:
df.duplicated().sum()

0

In [12]:
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,T,5,8,7,7,7,7,9,4,8,7,7,8,3,10,8,6
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [13]:
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
# Convert 'letter' to numeric labels
label_encoder = LabelEncoder()
df['letter'] = label_encoder.fit_transform(df['letter'])

C:\Users\dell\AppData\Local\Temp\ipykernel_39288\2262971375.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['letter'] = label_encoder.fit_transform(df['letter'])

In [18]:
# Verify encoding
print("Encoded Labels Sample:")
print(df['letter'].head())

Encoded Labels Sample:
0    19
1     8
2     3
3    13
4     6
Name: letter, dtype: int32

In [19]:
# Separate features and target variable
features = df.drop('letter', axis=1)  
labels = df['letter']

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler = MinMaxScaler()
features_normalized = scaler.fit_transform(features)

# 2. Model Implementation

In [22]:
X = df.drop('letter', axis=1)  # Features
Y = df['letter']  # Target variable

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [24]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [26]:
# Define the ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # Input layer and 1st hidden layer
    Dense(32, activation='relu'),  # 2nd hidden layer
    Dense(len(labels.unique()), activation='softmax')  # Output layer for classification
])

C:\Users\dell\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [27]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [28]:
# Train the model
history = model.fit(X_train, Y_train, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.1732 - loss: 3.0492 - val_accuracy: 0.5875 - val_loss: 1.5129
Epoch 2/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.6177 - loss: 1.3692 - val_accuracy: 0.6676 - val_loss: 1.1753
Epoch 3/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.6835 - loss: 1.0973 - val_accuracy: 0.7000 - val_loss: 1.0289
Epoch 4/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7206 - loss: 0.9356 - val_accuracy: 0.7208 - val_loss: 0.9430
Epoch 5/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7519 - loss: 0.8507 - val_accuracy: 0.7422 - val_loss: 0.8642
Epoch 6/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7620 - loss: 0.7930 - val_accuracy: 0.7626 - val_loss: 0.7957
Epoch 7/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7836 - loss: 0.7438 - val_accuracy: 0.7847 - val_loss: 0.7544
Epoch 8/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7889 - loss: 0.6927 - val_accuracy: 0.7918 - val_loss: 0.7022
Epoch 9/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8100 - loss: 0.6395 - val_accuracy: 0.7995 - val_loss: 0.6774
Epoch 10/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8186 - loss: 0.5961 - val_accuracy: 0.8042 - val_loss: 0.6493
Epoch 11/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8235 - loss: 0.5784 - val_accuracy: 0.8209 - val_loss: 0.6139
Epoch 12/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8364 - loss: 0.5505 - val_accuracy: 0.8165 - val_loss: 0.6076
Epoch 13/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8392 - loss: 0.5265 - val_accuracy: 0.8209 - val_loss: 0.5939
Epoch 14/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8424 - loss: 0.5249 - val_accuracy: 0.8058 - val_loss: 0.6018
Epoch 15/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8390 - loss: 0.5200 - val_accuracy: 0.8162 - val_loss: 0.5729
Epoch 16/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8449 - loss: 0.5100 - val_accuracy: 0.8179 - val_loss: 0.5944
Epoch 17/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8535 - loss: 0.4838 - val_accuracy: 0.8490 - val_loss: 0.5171
Epoch 18/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8612 - loss: 0.4609 - val_accuracy: 0.8390 - val_loss: 0.5112
Epoch 19/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8604 - loss: 0.4596 - val_accuracy: 0.8423 - val_loss: 0.5139
Epoch 20/20
374/374 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8603 - loss: 0.4525 - val_accuracy: 0.8356 - val_loss: 0.5438

In [29]:
model = Sequential([
    Dense(128, activation='tanh', input_shape=(X_train.shape[1],)),  # Increased neurons
    Dense(64, activation='tanh'),  # Modified activation
    Dense(len(labels.unique()), activation='softmax')
])

In [30]:
# Compile with a custom optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [31]:
# Train the model
history = model.fit(X_train, Y_train, epochs=50, batch_size=16, validation_split=0.2)  # More epochs, smaller batch size

Epoch 1/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.4079 - loss: 2.1932 - val_accuracy: 0.7004 - val_loss: 1.0928
Epoch 2/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7421 - loss: 0.9472 - val_accuracy: 0.7593 - val_loss: 0.8190
Epoch 3/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7851 - loss: 0.7524 - val_accuracy: 0.7975 - val_loss: 0.7018
Epoch 4/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8235 - loss: 0.6043 - val_accuracy: 0.8279 - val_loss: 0.5865
Epoch 5/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8528 - loss: 0.5146 - val_accuracy: 0.8537 - val_loss: 0.5190
Epoch 6/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8672 - loss: 0.4677 - val_accuracy: 0.8577 - val_loss: 0.4821
Epoch 7/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8815 - loss: 0.4036 - val_accuracy: 0.8621 - val_loss: 0.4475
Epoch 8/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8959 - loss: 0.3683 - val_accuracy: 0.8822 - val_loss: 0.4007
Epoch 9/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9052 - loss: 0.3304 - val_accuracy: 0.8828 - val_loss: 0.3816
Epoch 10/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9102 - loss: 0.3117 - val_accuracy: 0.8929 - val_loss: 0.3433
Epoch 11/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9190 - loss: 0.2843 - val_accuracy: 0.9069 - val_loss: 0.3185
Epoch 12/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9168 - loss: 0.2761 - val_accuracy: 0.8925 - val_loss: 0.3452
Epoch 13/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9263 - loss: 0.2514 - val_accuracy: 0.9006 - val_loss: 0.3117
Epoch 14/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9339 - loss: 0.2276 - val_accuracy: 0.9076 - val_loss: 0.2999
Epoch 15/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9321 - loss: 0.2244 - val_accuracy: 0.9183 - val_loss: 0.2644
Epoch 16/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9357 - loss: 0.2100 - val_accuracy: 0.9210 - val_loss: 0.2656
Epoch 17/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9454 - loss: 0.1919 - val_accuracy: 0.8945 - val_loss: 0.3312
Epoch 18/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9407 - loss: 0.1863 - val_accuracy: 0.9207 - val_loss: 0.2512
Epoch 19/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9448 - loss: 0.1818 - val_accuracy: 0.9136 - val_loss: 0.2648
Epoch 20/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9455 - loss: 0.1733 - val_accuracy: 0.9294 - val_loss: 0.2255
Epoch 21/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9456 - loss: 0.1706 - val_accuracy: 0.9260 - val_loss: 0.2357
Epoch 22/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9549 - loss: 0.1497 - val_accuracy: 0.9213 - val_loss: 0.2408
Epoch 23/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9541 - loss: 0.1474 - val_accuracy: 0.9243 - val_loss: 0.2300
Epoch 24/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.9536 - loss: 0.1489 - val_accuracy: 0.9354 - val_loss: 0.2076
Epoch 25/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9561 - loss: 0.1413 - val_accuracy: 0.9320 - val_loss: 0.2246
Epoch 26/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9561 - loss: 0.1372 - val_accuracy: 0.9217 - val_loss: 0.2564
Epoch 27/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9542 - loss: 0.1410 - val_accuracy: 0.9391 - val_loss: 0.2013
Epoch 28/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9607 - loss: 0.1313 - val_accuracy: 0.9367 - val_loss: 0.2042
Epoch 29/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9638 - loss: 0.1145 - val_accuracy: 0.9347 - val_loss: 0.2076
Epoch 30/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9655 - loss: 0.1137 - val_accuracy: 0.9330 - val_loss: 0.2087
Epoch 31/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9610 - loss: 0.1227 - val_accuracy: 0.9290 - val_loss: 0.2235
Epoch 32/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9622 - loss: 0.1187 - val_accuracy: 0.9294 - val_loss: 0.2255
Epoch 33/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9647 - loss: 0.1100 - val_accuracy: 0.9371 - val_loss: 0.1886
Epoch 34/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9690 - loss: 0.0982 - val_accuracy: 0.9351 - val_loss: 0.2020
Epoch 35/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9683 - loss: 0.1049 - val_accuracy: 0.9320 - val_loss: 0.2097
Epoch 36/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9721 - loss: 0.0928 - val_accuracy: 0.9451 - val_loss: 0.1921
Epoch 37/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.9718 - loss: 0.0945 - val_accuracy: 0.9354 - val_loss: 0.1941
Epoch 38/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9741 - loss: 0.0876 - val_accuracy: 0.9384 - val_loss: 0.1921
Epoch 39/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9754 - loss: 0.0805 - val_accuracy: 0.9344 - val_loss: 0.2085
Epoch 40/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9691 - loss: 0.0942 - val_accuracy: 0.9484 - val_loss: 0.1719
Epoch 41/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9735 - loss: 0.0883 - val_accuracy: 0.9340 - val_loss: 0.2075
Epoch 42/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9759 - loss: 0.0778 - val_accuracy: 0.9404 - val_loss: 0.1958
Epoch 43/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9743 - loss: 0.0796 - val_accuracy: 0.9294 - val_loss: 0.2262
Epoch 44/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9784 - loss: 0.0753 - val_accuracy: 0.9330 - val_loss: 0.2193
Epoch 45/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9715 - loss: 0.0809 - val_accuracy: 0.9394 - val_loss: 0.1944
Epoch 46/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9700 - loss: 0.0884 - val_accuracy: 0.9397 - val_loss: 0.2031
Epoch 47/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9803 - loss: 0.0672 - val_accuracy: 0.9417 - val_loss: 0.1896
Epoch 48/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.9810 - loss: 0.0632 - val_accuracy: 0.9314 - val_loss: 0.2103
Epoch 49/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9756 - loss: 0.0761 - val_accuracy: 0.9431 - val_loss: 0.1755
Epoch 50/50
747/747 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9783 - loss: 0.0666 - val_accuracy: 0.9374 - val_loss: 0.1953

# 3. Hyperparameter Tuning

In [33]:
import keras_tuner as kt

In [34]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(hp.Int('units', min_value=32, max_value=256, step=32), activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(len(labels.unique()), activation='softmax'))
    model.compile(optimizer=hp.Choice('optimizer', ['adam', 'sgd']),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [37]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=10)
tuner.search(X_train, Y_train, epochs=20, validation_split=0.2)

Reloading Tuner from .\untitled_project\tuner0.json

# 4. Evaluation

In [38]:
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
# Make predictions on the test set
y_pred = model.predict(X_test).argmax(axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

In [41]:
# Evaluate model performance
print("Classification Report:")
print(classification_report(Y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       144
           1       0.96      0.90      0.93       156
           2       0.97      0.94      0.95       147
           3       0.89      0.85      0.87       163
           4       0.93      0.94      0.93       144
           5       0.91      0.95      0.93       146
           6       0.92      0.90      0.91       173
           7       0.78      0.92      0.84       133
           8       0.87      0.96      0.92       108
           9       0.90      0.92      0.91       150
          10       0.90      0.97      0.94       149
          11       0.97      0.95      0.96       147
          12       0.97      0.98      0.98       143
          13       0.94      0.97      0.96       138
          14       0.92      0.95      0.94       131
          15       0.95      0.94      0.94       161
          16       0.94      0.96      0.95       145
          17       0.98      0.88      0.93       147
          18       0.99      0.92      0.96       142
          19       0.99      0.90      0.94       151
          20       0.97      0.93      0.95       143
          21       0.90      0.97      0.94       155
          22       0.99      0.98      0.98       133
          23       0.99      0.94      0.96       124
          24       0.96      0.98      0.97       138
          25       0.99      0.95      0.97       123

    accuracy                           0.94      3734
   macro avg       0.94      0.94      0.94      3734
weighted avg       0.94      0.94      0.94      3734

In [43]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred))

Confusion Matrix:
[[144   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [  0 140   0   4   1   0   2   2   0   0   0   0   0   0   0   2   1   0
    0   0   0   4   0   0   0   0]
 [  1   0 138   0   0   0   1   0   0   0   0   0   2   1   3   0   0   0
    0   0   1   0   0   0   0   0]
 [  0   2   0 139   1   0   0   9   0   2   1   0   1   3   4   0   1   0
    0   0   0   0   0   0   0   0]
 [  0   1   2   0 135   0   4   0   0   0   1   0   0   0   0   1   0   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   1   0 139   0   1   2   1   0   0   0   0   0   1   0   0
    0   1   0   0   0   0   0   0]
 [  0   0   3   3   7   0 155   1   0   0   1   0   0   0   1   0   1   0
    0   0   0   0   1   0   0   0]
 [  0   0   0   2   0   1   0 122   0   2   2   0   0   1   0   0   2   1
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 104   3   0   0   0   0   0   1   0   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   1   0   1   9 138   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   2   0   0 145   1   0   0   0   0   0   1
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   2   3   0   0   2 139   0   0   0   1   0   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0 140   0   0   0   0   0
    0   0   0   3   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0 134   1   0   0   0
    0   0   0   2   0   0   0   0]
 [  0   0   0   1   0   0   2   2   0   0   0   0   0   0 125   0   1   0
    0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   5   0   1   1   0   0   1   0   0   0 151   0   0
    0   0   0   0   0   0   2   0]
 [  1   0   0   1   0   0   2   0   0   1   0   0   0   0   1   0 139   0
    0   0   0   0   0   0   0   0]
 [  1   1   0   2   0   0   0   7   0   0   3   0   0   3   0   0   0 129
    0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   3   0   0   1   0   2   2   0   0   0   0   1   0
  131   0   0   0   0   0   0   1]
 [  0   0   0   0   0   4   0   2   1   0   0   0   0   0   0   1   0   0
    0 136   1   2   0   1   3   0]
 [  1   0   0   1   0   0   0   2   0   2   0   0   1   0   0   0   0   0
    0   0 133   3   0   0   0   0]
 [  0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   1   0   0
    0   0   1 151   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
    0   0   1   1 130   0   0   0]
 [  1   0   0   0   0   0   0   0   1   1   4   1   0   0   0   0   0   0
    0   0   0   0   0 116   0   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0
    0   0   0   1   0   0 135   0]
 [  0   0   0   0   1   0   0   0   0   3   0   0   0   0   0   0   1   0
    1   0   0   0   0   0   0 117]]